name: Deploy to Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Ubuntu Host (Swarm)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 30s
          command_timeout: 15m
          script: |
            set -e
            cd /opt/iacloudacess
            echo "Pulling latest changes from Git..."
            git pull origin main
            
            echo "Building API image..."
            docker build -t school-access-api:latest -f Dockerfile .
            
            echo "Building Frontend image..."
            docker build -t school-access-frontend:latest -f Dockerfile.frontend .
            
            echo "Deploying Docker Stack..."
            export $(grep -v '^#' .env | xargs) && docker stack deploy -c docker-stack.yml school --with-registry-auth
            
            echo "Deployment successful."
